### ISSUE TITLE
Path to JUCE Modules Incorrect

### ISSUE THREAD

**Issue by jakepenn** [samgerike/MTEC_498_698#1]
Hey Sam -- 

Please delete the JUCE modules from your download folder and try to compile your project, they'll no longer be found. 

If you can update the modules path in your JUCER to point to the modules in your repo that should be resolved, I'll hold off on grading until you get that resolved

**Comment by samgerike** [comment]
i usually keep my download folder empty and i just deleted the JUCE files from there.

i updated the paths accordingly but i'm still having trouble. i'll try figuring it out right now

**Comment by samgerike** [comment]
> Hey Sam --
> 
> Please delete the JUCE modules from your download folder and try to compile your project, they'll no longer be found.
> 
> If you can update the modules path in your JUCER to point to the modules in your repo that should be resolved, I'll hold off on grading until you get that resolved

nevermind... i was updating file paths on xcode and not JUCE. should be fixed and pushed now.

**Comment by jakepenn** [comment]
nice work! -- sorry I missed your reply!
